yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace="posts")),
    path('about/', include('about.urls', namespace='about'))
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# if settings.DEBUG:
#     import debug_toolbar

#     urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              related_name='posts',
                              on_delete=models.SET_NULL
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата написания комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user_following'
            )
        ]

yatube/posts/forms.py
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = {'text', 'group', 'image'}
        labels = {
            'text': _('Текст поста'),
            'group': _('Название группы')
        }
        help_text = {
            'text': _('Это просто текст поста'),
            'group': _('А это просто название группы')
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Post, Group, User, Follow
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.conf import settings


def index(request):
    post_list = Post.objects.all().select_related('author').order_by(
        '-pub_date')
    paginator = Paginator(post_list, settings.POSTS_MAX)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('author')
    paginator = Paginator(posts, settings.POSTS_MAX)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    following = False
    author = get_object_or_404(User, username=username)
    following = (
        request.user.is_authenticated and Follow.objects.filter(
            user=request.user, author=author).exists()
    )
    user_posts = author.posts.select_related('author').order_by('-pub_date')
    paginator = Paginator(user_posts, settings.POSTS_MAX)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'user_posts': user_posts,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author_posts = (Post.objects.select_related('author')
                    .filter(author=post.author))
    author_posts_count = author_posts.count()
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'author_posts': author_posts,
        'author_posts_count': author_posts_count,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
        return render(request, 'posts/create_post.html', {'form': form})
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': is_edit,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    following = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(following, settings.POSTS_MAX)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    following_author = get_object_or_404(User, username=username)
    if request.user != following_author:
        Follow.objects.get_or_create(user=request.user,
                                     author=following_author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    following_author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=following_author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if not post %} Новый пост {% else %} Редактировать пост {% endif %}{% endblock %}
{% block content %}
  {% load user_filters%}
  <div class="container py-5"> 
    <div class="row justify-content-center"> 
      <div class="col-md-8 p-5"> 
        <div class="card"> 
          <div class="card-header"> 
            {% if is_edit %}  
              Редактировать пост 
            {% else %} 
              Новый пост 
            {% endif %} 
          </div>
          <div class="card-body">
            {% if is_edit %} 
              <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
            {% else %} 
              <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
            {% endif %}  
            {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                    {{ field|addclass:"form-control" }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end"> 
                <button type="submit" class="btn btn-primary"> 
                  {% if is_edit %} 
                    Сохранить 
                  {% else %} 
                    Добавить 
                  {% endif %}  
                </button>
              </form>
            </div> 
          </div> 
        </div>
      </div> 
    </div> 
  </div> 
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% load static %}
  {% block title %}Лента подписки{% endblock %}
  {% block content %}
    <div class="container py-5">
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/article.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
<title> {% block title %} {{title}} {% endblock %}</title>
{% block content %}
<div class="container py-5">
  <p>{{ group.description }}</p>
  <h1>{{group}}</h1>
  {% for post in page_obj %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% include 'includes/post.html' with link=False %}
    {% if not forloop.last %} <hr> {% endif %}
  {%endfor%}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% load static %}
  {% load cache %}
  {% block title %} Последние обновления на сайте {% endblock %}
  {% block content %}
    <div class="container py-5">
      {% cache 20 index_page %}
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/article.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
      {% endcache %}
    </div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
<title> {% block title %} Пост {{ post.text | truncatechars:30 }} {% endblock %}</title>
{% include 'includes/header.html' %}
{% block content %}
<main>
  <div class="row container py-5">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{post.pub_date|date:"d E Y"}}
        </li>
        {%if post.group%}  
        <li class="list-group-item">
          Группа: {{post.group.slug}}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы {{post.group.title}}
          </a>
        </li>
        {%endif%}
        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{user.posts.count}}</span>
        </li>
        {% if post.user.username %}
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        {% endif %}
      </ul>
    </aside>
  
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">Редактировать запись</a>
      {% endif %}
      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %} 
    </article>
  </div>
</main>


{% endblock %}
{% include 'posts/includes/paginator.html' %}
{% include 'includes/footer.html' %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  {% block title %} Профайл пользователя {{ author }} {% endblock %}
  {% block content %}
  {% load thumbnail %}
    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        <h3>Подписчиков: {{ author.following.count }}</h3>
        {% if request.user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
          {% endif %}
        {% endif %}
      </div>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          {% if post.group %}
            <p>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>